fix(datetime-picker): update base class and add logic to work with la…
Refinitiv/refinitiv-ui pull request #1088
Opened 2024-01-18 09:05 UTC by kosol-komenek-rft

Description
Datetime picker change base class from ControlElement to FormFieldElement.

Fixes # (issue) https://jira.refinitiv.com/browse/ELF-2348

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-01-28 16:07 UTC, Theeraphat-Sorasetsakul submitted a review, later dismissed
LGTM.

2024-01-29 07:11 UTC, bualoy-napat commented
Verified!

2024-01-29 08:59 UTC, wattachai-lseg requested changes
It seems this PR faces the same issue as described in https://github.com/Refinitiv/refinitiv-ui/pull/1079#pullrequestreview-1848129293. Let's address it before merge.

2024-02-09 10:34 UTC, wattachai-lseg commented on packages/elements/src/datetime-picker/locales.ts
> +// for 5 langauge is set in Phrasebook de / en / ja / zh / zh-hant
```suggestion
// de, en, ja, zh & zh-hant have been defined in Phrasebook already.
```

2024-02-09 10:46 UTC, wattachai-lseg approved these changes

2024-02-09 11:14 UTC, merged