fix: missing scrollbar custom style on Chrome 121
Refinitiv/refinitiv-ui pull request #1103
Opened 2024-02-14 02:13 UTC by bualoy-napat

## Description
Chrome 121 introduces support for [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) and [scrollbar-width](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width). Using any of these property would disable ::-webkit-scrollbar styling. Although EF uses these properties to style scrollbar just for Firefox, it also applies to Chrome 121+ disabling ::-webkit-scrollbar styling.

Fixes # (issue)
[DME-6491](https://jira.refinitiv.com/browse/DME-6491)

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-02-15 10:42 UTC, wattachai-lseg approved these changes, later dismissed

2024-02-16 09:17 UTC, wattachai-lseg requested changes
a few more things.

2024-02-16 09:17 UTC, wattachai-lseg commented on packages/elemental-theme/src/shared-styles/scrollbar.less
> +}
Let's move these 2 mixins to the bottom after `.scrollbars()`

2024-02-16 09:17 UTC, wattachai-lseg commented on packages/elemental-theme/src/shared-styles/scrollbar.less
> +// `.mozilla-scrollbars()` is deprecated. Use `standard-scrollbars` instead.
```suggestion
// `.mozilla-scrollbars()` is deprecated. Use `.standard-scrollbars()` instead.
```

2024-02-16 09:17 UTC, wattachai-lseg commented on packages/elemental-theme/src/shared-styles/scrollbar.less
> + */
```suggestion
// `.scrollbars()` is deprecated. Use `.standard-scrollbars()` and `.webkit-scrollbars()` instead.
```

2024-02-16 09:17 UTC, wattachai-lseg commented on packages/halo-theme/src/shared-styles/scrollbar.less
> +.standard-scrollbars() {
let's apply the same change of `packages/elemental-theme/src/shared-styles/scrollbar.less` to here.

2024-02-16 09:17 UTC, wattachai-lseg commented on packages/elemental-theme/src/shared-styles/scrollbar.less
> +.standard-scrollbars() {
add the following comment:

```
/*
  While `.standard-scrollbars()` requires a selector to apply CSS properties, `.webkit-scrollbars()` could be used directly as it utilizes CSS pseudo-elements.
  Here's a usage example with web component:

::host {
  .standard-scrollbars();
}
.webkit-scrollbars();

*/
```

2024-02-16 10:15 UTC, bualoy-napat commented on packages/elemental-theme/src/shared-styles/scrollbar.less
> +.standard-scrollbars() {
fixed

2024-02-16 10:21 UTC, wattachai-lseg approved these changes

2024-02-16 11:05 UTC, Theeraphat-Sorasetsakul commented
Verified.

2024-02-16 13:19 UTC, merged