fix(datetime-picker): validate values for weekendsonly and weekdaysonly
Refinitiv/refinitiv-ui pull request #1117
Opened 2024-03-07 03:04 UTC by bualoy-napat

## Description

Previously, datetime-picker was not validating values that within condition of `weekends-only` and `weekdays-only`. To fix this issue, we just simply add validation of `weekdays-only` and `weekends-only` to `validateInput` method. This method will be calling every time that input has change.

Fixes # (issue)
DME-9462

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-03-07 13:40 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/datetime-picker/__test__/datetime-picker.value.test.js
> +    it('It must error when weekends-only is set and value is not in weekend period', async function () {
```suggestion
    it('It should error when weekends-only is true and value is not in weekend period', async function () {
```

2024-03-07 13:40 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/datetime-picker/__test__/datetime-picker.value.test.js
> +    it('It must error when weekdays-only is set and value is not in weekday period', async function () {
```suggestion
    it('It should error when weekdays-only is true and value is not in weekday period', async function () {
```

2024-03-07 13:40 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/datetime-picker/__test__/datetime-picker.value.test.js
> +    it('It must error when weekends-only is set and values are not in weekend period with range mode', async function () {
```suggestion
    it('It should error when weekends-only is true and values are not in weekend period with range mode', async function () {
```

2024-03-07 13:40 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/datetime-picker/__test__/datetime-picker.value.test.js
> +    it('It must error when weekdays-only is set and values are not in weekday period with range mode', async function () {
```suggestion
    it('It should error when weekdays-only is true and values are not in weekday period with range mode', async function () {
```

2024-03-11 02:21 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/datetime-picker/__test__/datetime-picker.value.test.js
> +        'error state should return to false when both inputs value are valid'
Shouldn't do multiple expect in one test case. And this Sound like multiple test cases.

2024-03-11 03:35 UTC, Theeraphat-Sorasetsakul submitted a review, later dismissed

2024-03-11 07:04 UTC, wattachai-lseg requested changes

2024-03-11 07:04 UTC, wattachai-lseg commented on packages/elements/src/datetime-picker/index.ts
> +  private isAllowSelectedDay(): boolean {
```suggestion
  private isValidDay(): boolean {
```

2024-03-11 07:04 UTC, wattachai-lseg commented on packages/elements/src/datetime-picker/index.ts
`shouldValidateValue()` should detect change of `weekdaysOnly` & `weekendsOnly` as well.

2024-03-11 07:33 UTC, wattachai-lseg commented on packages/elements/src/datetime-picker/__test__/datetime-picker.value.test.js
Let's add a comment describing that <input> value update testing relies on blur event which can't be simulated due to the implementation of focus registry. There should be some existing similar comments in unit test suite. Let's copy it over.

2024-03-11 08:25 UTC, wattachai-lseg approved these changes

2024-03-11 08:37 UTC, merged