fix(tooltip): handle body removal
Refinitiv/refinitiv-ui pull request #1131
Opened 2024-03-20 09:06 UTC by Theeraphat-Sorasetsakul

## Description

Handle the removal with body existence check. Optional chaining e.g. `document.body?.<prop-name>` is quite handy for this.

Fixes # ([DME-2103](https://jira.refinitiv.com/browse/DME-2103))

**Expected:**
- EF should be fail safe in case of body removal.
- Body existence check should be commented that it's for body removal handling. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-03-21 08:13 UTC, wattachai-lseg requested changes

2024-03-21 08:13 UTC, wattachai-lseg commented on packages/elements/src/overlay/managers/interaction-lock-manager.ts
> +      this.scrollLeft = document.scrollingElement?.scrollLeft || 0;
let's revert this one similar to v7 PR.

2024-03-21 08:18 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/overlay/managers/interaction-lock-manager.ts
> +      this.scrollLeft = document.scrollingElement?.scrollLeft || 0;
Fixed.

2024-03-21 08:23 UTC, wattachai-lseg submitted a review, later dismissed

2024-03-28 10:56 UTC, wattachai-lseg approved these changes

2024-03-28 12:19 UTC, merged