Fix/register error dev env v6
Refinitiv/refinitiv-ui pull request #1156
Opened 2024-05-02 10:09 UTC by bualoy-napat

## Description
To prevent element to throw error when custom element into registry on the production, we need to check environment before throw error to notice the developer.

Fixes # (issue)
DME-14858

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-05-02 11:08 UTC, wattachai-lseg requested changes
A few more things on test coverage.

2024-05-02 11:08 UTC, wattachai-lseg commented on packages/core/__test__/utils/elementReady.test.js
> +    expect(errorMessage).to.equal('test', 'duplication error not thrown');
```suggestion
    expect(errorMessage).to.equal('test', 'test error not thrown');
```

2024-05-02 11:08 UTC, wattachai-lseg commented on packages/core/src/registries/CustomStyleRegistry.ts
> +      if (isLocalhost) {
`/* istanbul ignore else  */` on top of if statement instead of `/* istanbul ignore next */` should be better.

2024-05-02 11:08 UTC, wattachai-lseg commented on packages/core/src/registries/NativeStyleRegistry.ts
> +      if (isLocalhost) {
`/* istanbul ignore else  */` on top of if statement instead of `/* istanbul ignore next */` should be better.

2024-05-03 02:22 UTC, bualoy-napat commented on packages/core/src/registries/CustomStyleRegistry.ts
> +      if (isLocalhost) {
Done

2024-05-03 02:22 UTC, bualoy-napat commented on packages/core/__test__/utils/elementReady.test.js
> +    expect(errorMessage).to.equal('test', 'duplication error not thrown');
Done

2024-05-03 02:22 UTC, bualoy-napat commented on packages/core/src/registries/NativeStyleRegistry.ts
> +      if (isLocalhost) {
Done

2024-05-03 02:58 UTC, wattachai-lseg commented on packages/core/src/registries/CustomStyleRegistry.ts
> +      if (isLocalhost) {
Looks like we need both. 🤦  Could you bring back `/* istanbul ignore next */` as well.

2024-05-03 02:59 UTC, wattachai-lseg commented on packages/core/src/registries/NativeStyleRegistry.ts
> +      if (isLocalhost) {
Looks like we need both. 🤦  Could you bring back `/* istanbul ignore next */` as well.

2024-05-03 03:02 UTC, wattachai-lseg commented on packages/core/src/registries/ElementRegistry.ts
> +  if (isLocalhost || !isElementDefined) {
This should improve test coverage.
```suggestion
  if (isLocalhost ||
      /* istanbul ignore next */ !isElementDefined) {
```

2024-05-03 03:12 UTC, wattachai-lseg commented on packages/core/src/registries/ElementRegistry.ts
> +  if (isLocalhost || !isElementDefined) {
confirmed that it doesn't improve test coverage. Marking as resolved.

2024-05-03 03:36 UTC, wattachai-lseg approved these changes

2024-05-03 08:29 UTC, Theeraphat-Sorasetsakul commented
Verified.

2024-05-03 08:42 UTC, merged