fix(slider): sync emitted value and input value
Refinitiv/refinitiv-ui pull request #1198
Opened 2024-07-23 09:11 UTC by prima-lseg

## Description

Emitted value doesn't match with value that show on input.

Fixes # (issue)
[DME-17777](https://jira.refinitiv.com/browse/DME-17777)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2024-07-31 16:01 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/slider/elements/slider.ts
> +    if (this.isValueInBoundary(this.fromNumber + this.minRangeNumber, SliderDataName.from)) {
Can you move this logic to `isValueInBoundary`? Do that to both onFromChange and onTochange.

2024-07-31 16:01 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/slider/elements/slider.ts
> +      this.notifyPropertyChange(name, adjustedValue);
```suggestion
      this[name] = calculateValue(this.format(valueNumber));
      this.notifyPropertyChange(name, this[name]);
```

2024-08-01 03:13 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/slider/elements/slider.ts
> +    if (this.isValueInBoundary(this.fromNumber + this.minRangeNumber, SliderDataName.from)) {
I mean move only logic of the new change.

2024-08-07 08:17 UTC, wattachai-lseg requested changes

2024-08-07 08:17 UTC, wattachai-lseg commented on packages/elements/src/slider/elements/slider.ts
> +    // From and to value is calculate with min range
```suggestion
    // adjust update-pending from/to value based on min range
```

2024-08-07 08:17 UTC, wattachai-lseg commented on packages/elements/src/slider/elements/slider.ts
> +    const calculateValue = (currentValue: string): string => {
* `adjustValue` should be a better name than `calculateValue`.
* keep it simple with `value` instead of `currentValue`?

2024-08-07 08:17 UTC, wattachai-lseg commented on packages/elements/src/slider/elements/slider.ts
> +
let's add a comment: "revert number field value back to the pre-update value".

2024-08-07 08:17 UTC, wattachai-lseg commented on packages/elements/src/slider/elements/slider.ts
>          return false;
As both conditions return `false`, let's combine them.
Here's an idea:

```javascript
const isFromOutOfBound = ...;
const isToOutOfBound = ...;
if (isFromOutOfBound || isToOutOfBound) { return false; }
```

2024-08-07 08:17 UTC, wattachai-lseg commented on packages/elements/src/slider/elements/slider.ts
> +    // recalculate value and check boundary before rounding
Let's replace the current "what" comment why "comment" as written below.
```javascript
/** 
 * This method handles "to" value change triggered by 
 * both user interaction and programmatic update.
 * 
 * In case of user interaction update, 
 * the value would be adjusted by min range before entering this method. 
 * That adjustment needs to be reverted.
 * 
 * In case of programmatic value update, 
 * This method could handle the revert although there is no prior adjustment.
*/

2024-08-07 08:17 UTC, wattachai-lseg commented on packages/elements/src/slider/elements/slider.ts
> +    // recalculate value and check boundary before rounding
Let's replace the current "what" comment why "comment" as written below.
```javascript
/** 
 * This method handles "from" value change triggered by 
 * both user interaction and programmatic update.
 * 
 * In case of user interaction update, 
 * the value would be adjusted by min range before entering this method. 
 * That adjustment needs to be reverted.
 * 
 * In case of programmatic value update, 
 * This method could handle the revert although there is no prior adjustment.
*/

2024-08-08 02:17 UTC, wattachai-lseg commented on packages/elements/src/slider/elements/slider.ts
> +    // Revert number field value back to the pre-update value
Actually, "revert" doesn't completely cover what is happening here. My bad. Let's revise the comment.
```suggestion
    // Sync number field value with its component property counterpart
```

2024-08-08 03:14 UTC, wattachai-lseg approved these changes

2024-08-08 03:20 UTC, merged