fix(tree): tree query selection issues
Refinitiv/refinitiv-ui pull request #361
Opened 2022-06-13 08:37 UTC by Nantawat-Poothong

## Description
Tree fire incorrect item in `value-changed` event, when using tree `query` property.

The problem is when filtering items, the exclude item will be locked and can't perform any action.

This PR made 2 changes
1. Only lock the item in single selection mode.
2. Re-filter items when selection mode change.

Fixes # (issue)
https://jira.refinitiv.com/browse/ELF-1851

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2022-06-13 15:58 UTC, wsuwt commented on packages/elements/src/tree/__test__/tree.test.js
> +    it('Text filter applied, single selection', async () => {
I would update the test case name into something like 
```suggestion
    it('Should be able to select value after filter is applied', async () => {
```

2022-06-13 15:58 UTC, wsuwt commented on packages/elements/src/tree/managers/tree-manager.ts
> +   * @param lock Item lock
It would be great to explain why we need this extra parameter.

2022-06-14 02:24 UTC, Nantawat-Poothong commented on packages/elements/src/tree/managers/tree-manager.ts
> +   * @param lock Item lock
Thank you, updated!

2022-06-14 08:29 UTC, goremikins requested changes
This fix does not look right to me. It needs to be discussed in Tech session.

2022-06-15 10:16 UTC, closed without merging