feat(interactive-chart): add disabledLegend option to hide legend
Refinitiv/refinitiv-ui pull request #421
Opened 2022-08-02 08:03 UTC by Nantawat-Poothong

## Description
User can not hide dash text (--) when hovers on the point that doesn't have the data.

Solution
- revert previous solution #402 
- add `disabledLegend` option to hide both `price` and `symbol` in series data

Fixes # (issue)
https://jira.refinitiv.com/browse/ELF-1932

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2022-08-02 08:42 UTC, dtanp-rft commented
- We shouldn't use negate variable i.e. disabledLegend = true. Instead, use legendVisible = false to hide series legend. The name is consistent with `visible` in lightweight trading view series config.
```
          seriesOptions: {
            priceScaleId: 'right',
            visible: false
          },
```
- New test case is fine but better to add one more test to have multiple series and hide legend of some series, test should check if legend of those series are hidden.

Anything else looks good to me. @Sarin-Udompanish can you help me to review this PR please?

2022-08-02 08:43 UTC, dtanp-rft requested changes
Please see my comment.

2022-08-02 08:46 UTC, dtanp-rft requested changes, later dismissed

2022-08-02 08:46 UTC, dtanp-rft commented on documents/src/pages/elements/interactive-chart.md
> +In case you want to hide the `price` and `symbol`, use `disabledLegend`. The chart will hide the `price` and `symbol` either.
```suggestion
Use `legendVisible` to hide a legend of any series.
```

2022-08-02 08:46 UTC, dtanp-rft commented on documents/src/pages/elements/interactive-chart.md
> +      disabledLegend: true,
```suggestion
      legendVisible: false,
```

2022-08-02 08:52 UTC, Nantawat-Poothong commented
> * We shouldn't use negate variable i.e. disabledLegend = true. Instead, use legendVisible = false to hide series legend. The name is consistent with `visible` in lightweight trading view series config.
> 
> ```
>           seriesOptions: {
>             priceScaleId: 'right',
>             visible: false
>           },
> ```
@dtanp-rft 
I hesitate between `disabledLegend ` and `legendVisible` because I found that in our docs API also have property `disabled-legend` to hide whole chart legend. So I think the new option name should be relate to this.

But it's also make sense to consistent with `visible` in lightweight trading view series config.

2022-08-09 08:41 UTC, Sarin-Udompanish approved these changes

2022-08-09 08:47 UTC, merged