feat(clock): small analogue clock face
Refinitiv/refinitiv-ui pull request #54
Opened 2021-10-28 15:23 UTC by bualoy-napat

## Description
A new feature on the clock. When the width is less than 130px, the face of the clock will change to a smaller face that is easy to read.

Update UI of digital and analog clock to match with current spec from UX.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2021-11-01 03:36 UTC, dtanp-rft commented on packages/elements/src/clock/index.ts
> +    this.requestUpdate();
Ah that's right! I think this is a good solution as we have discussed that `size` can be (hidden) prop. We should try to go with this approach.

2021-11-01 08:23 UTC, bualoy-napat commented on packages/elements/src/clock/index.ts
> +    this.requestUpdate();
Thank you for your suggestion. It's very helpful.

2021-11-01 10:09 UTC, bualoy-napat commented on packages/elements/src/clock/index.ts
> +
Already fix in recently commit.

2021-11-01 10:11 UTC, bualoy-napat commented on packages/elements/src/clock/__test__/clock.analogue.test.js
> +      expect(el.hasAttribute('size')).to.equal(true, 'attribute "size" should be present');
I have already improved on this point with a recent commit.

2021-11-03 01:32 UTC, dtanp-rft requested changes
I think `size=small` should not be added if it's not analog clock.
Would you please change it and write test for this change?

Regarding to the test, I suggest you breakdown test case to be smaller test. When test is failed, it's easier to understand what is going wrong e.g.

**Shows small size clock when width is less than 130px**
1. test if [part=digital] is rendered if width >= 130px
2. set width < 130px
3. test if [part=digital] is not rendered
4. test if [part="segment am-pm"] is rendered (ps. I wouldn't bother to check if it needs to be inside [part="hands"] but it's fine if you want the test is a little bit strict

**Small size clock show AM/PM if it has attribute `am-pm`**
1. Use el = await fixture('<ef-clock am-pm analogue></ef-clock>');
2. Set width <= 130px 
3. Test if am-pm part is rendered

**Attribute `size=small` shouldn't show if it's not analog clock**
1. el = await fixture('<ef-clock></ef-clock>');
2. Set width < 130px
3. Test if `size=small` is not present
4. Set width >= 130px
5. Test if `size=small` is not present

2021-11-03 07:26 UTC, dtanp-rft approved these changes
Please squash commit when merge.

2021-11-03 07:59 UTC, merged