Refactor event description in all elements
Refinitiv/refinitiv-ui pull request #551
Opened 2022-12-15 08:48 UTC by bualoy-napat

## Description

Some content in event section was misled. We need to review and refactor the event section in all elements

## Type of change

Please delete options that are not relevant.
- [x] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2022-12-21 07:41 UTC, wattachai-lseg requested changes
Most of the issues are
* "the" user
* ~~by~~ programmatically
* single verb form for "the user"

There are just a few items requiring special attentions.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/appstate-bar/index.ts
> + * @fires clear - Fired when user tapped clear button.
Fired when "the" user taps~~ped~~ the clear button.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/autosuggest/index.ts
> - * @fires item-highlight Fired when an item gets highlighted or highlight is removed
missing hyphen between event names and their descriptions?

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/autosuggest/index.ts
> + * @fires item-highlight Fired when user highlighted an item or remove highlight from the item.
"the" user highlights~~ed~~ an item or remove"s" highlight

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/autosuggest/index.ts
> + * @fires item-select Fired when user selected an item on autosuggest.
"the" uses select"s"~~ed~~

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/autosuggest/index.ts
> + * @fires suggestions-query Fired when user changed value in input control and you might need to update suggestion item accordingly.
* "the" user change"s"~~d~~ value in input control.
* you might need to update suggestion item"s" accordingly

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/autosuggest/index.ts
> + * @fires suggestions-changed Fired when suggestions data changed.
suggestion~~s data~~ "items"?

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/button/index.ts
> + * @fires active-changed - Fired when `active` property changed by user taps on toggled button. It will not be triggered if `active` state is changed by programmatically.
* does "toggled button" imply that `toggles` prop is `true`? If that's the case, it should be described explicitly.
* It will not be triggered if `active` state is changed ~~by~~ programmatically

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/calendar/index.ts
> + * @fires value-changed - Fired when the user commits a date change. The event is not triggered if `value` is changed by programmatically.
for both line 97 & 98, remove "by": ...is changed ~~by~~ programmatically

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/canvas/index.ts
> + * @fires frame - Fired when next Frame event occurs when autoloop is set to true
Fired when next Frame event occurs ~~when~~ "and" autoloop is set to true?

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/card/index.ts
> + * @fires item-trigger - Fired when user selects card menu.
"the" user selects card menu.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/checkbox/index.ts
> + * @fires checked-changed - Fired when the user checked or unchecked the checkbox. The event is not fired if the `checked` property is changed by programmatically.
Fired when the user checks~~ed~~ or unchecks~~ed~~ the checkbox. The event is not fired if the `checked` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/clock/index.ts
> + * @fires offset-changed - Fired when user offsets the clock in `interactive` mode. The event is not triggered if `offset` property is changed by programmatically.
.."the" user offsets the clock in `interactive` mode. The event is not triggered if `offset` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/collapse/index.ts
> + * @fires expanded-changed - Fired when the user expanded or collapsed the control. The event is not triggered if `expanded` property is changed by programmatically.
Fired when the user expands~~ed~~ or collapses~~d~~ the control. The event is not triggered if `expanded` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/color-dialog/index.ts
> + * @fires value-changed - Fired when the user commits a value change. The event is not triggered if the value is changed by programmatically.
The event is not triggered if the value is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/color-dialog/index.ts
> + * @fires opened-changed - Fired when the user changed open state of the dialog e.g. when users press escape or use close button to close the dialog. The event is not triggered if `opened` property i
Fired when the user changes~~d~~ open state of the dialog e.g. when "the" user~~s~~ press"es" escape "key" or use"s" close button to close the dialog. The event is not triggered if `opened` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/color-picker/index.ts
> + * @fires value-changed - Fired when the user commits a value change. The event is not triggered if `value` property is changed by programmatically.
The event is not triggered if `value` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/combo-box/index.ts
> + * @fires value-changed - Fired when the user commits a value change. The event is not triggered if `value` property is changed by programmatically.
69 to 71: ...property is changed ~~by~~ programmatically

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/combo-box/index.ts
> + * @fires query-changed - Fired when the user changed value in the input to change a query word. The event is not triggered if `query` property is changed by programmatically.
* Fired when the user change"s"~~d~~ value...
* I find this description incomplete. Maybe we should mention that this `query-changed` comes from [input event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event). Plus, it fires after a delay set by`query-debounce-rate`?

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/datetime-picker/index.ts
> + * @fires value-changed - Fired when user commits a value change. The event is not triggered if `value` property is changed by programmatically.
87 & 88: ...property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/datetime-picker/index.ts
> + * @fires view-changed - Fired when user changed view in calendar e.g. change to next month view.
Fired when "the" user changes~~d~~ view in calendar

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/dialog/index.ts
> + * @fires opened-changed - Fired when the user changed open state of the dialog e.g. when users press escape or use close button to close the dialog. The event is not triggered if `opened` property i
Fired when the user changes~~d~~ open state of the dialog e.g. when "the" user~~s~~ press"es" escape "key" or use"s" close button to close the dialog. The event is not triggered if `opened` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/email-field/index.ts
> + * @fires value-changed - Fired when user commits a value change. The event is not triggered if `value` property is changed by programmatically.
* 11 & 12: ...property is changed ~~by~~ programmatically.
* Fired when "the" user commits a value change

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/email-field/index.ts
> + * @fires error-changed - Fired when user inputs invalid value. The event is not triggered if `error` property is changed by programmatically.
Fired when "the" user inputs "an" invalid value. T

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/email-field/index.ts
> + * @fires icon-click - Fired when user tapped on icon that added into control's slot.
Fired when "the" user taps~~ped~~ on icon ~~that~~ added into control's slot.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/list/elements/list.ts
> + * @fires value-changed - Fired when the user commits a value change. The event is not triggered if `value` property is changed by programmatically.
property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/multi-input/index.ts
> + * @fires value-changed - Fired when the user added new pill or removed pill. The event is not triggered if `value` property is changed by programmatically.
29 to 32: 
* align all of them with '"the" user'
* verbs for "the user" should be singular not past simple. 
* ...is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/multi-input/index.ts
> + * @fires item-error - Fired when item that attempt to add is invalid.
Fired when item ~~that~~ attempt"ing" to add is invalid.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/notification/elements/notification.ts
> + * @fires collapsed - Fired when notification is collapsed.
there should be no full stop here.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/notification/elements/notification.ts
> + * @fires dismiss - Fired when the user tapped close button to dismiss notification. The event is not triggered if the dismiss is done by programmatically.
Fired when the user tap"s"~~ped~~ close button to dismiss notification. The event is not triggered if the dismiss is done ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/number-field/index.ts
> + * @fires value-changed - Fired when user commits a value change. The event is not triggered if `value` property is changed by programmatically.
32 & 33: property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/overlay-menu/index.ts
> + * @fires item-trigger - Fired when user tapped on item.
Fired when "the" user tap"s"~~ped~~ on item~~.~~

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/overlay-menu/index.ts
> + * @fires opened-changed - Fired when the user changed open state of the overlay e.g. when users press escape or use close button to close the overlay. The event is not triggered if `opened` property
Fired when the user changes~~d~~ open state of the overlay e.g. when "the" user~~s~~ press"es" escape "key" or use"s" close button to close the overlay. The event is not triggered if `opened` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/overlay/elements/overlay.ts
> + * @fires opened-changed - Fired when the user changed open state of overlay e.g. when users press escape or use close button to close the overlay. The event is not triggered if `opened` property is
Fired when the user change"s"~~d~~ open state of overlay e.g. when "the" user~~s~~ press"es" escape "key" or use"s" close button to close the overlay. The event is not triggered if `opened` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/pagination/index.ts
> + * @fires value-changed - Fired when user interacts with the control to change pages and so the `value` property changed. The event is not triggered if `value` is changed by programmatically.
Fired when "the" user interacts with the control to change pages and so the `value` property changed. The event is not triggered if `value` is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/password-field/index.ts
> + * @fires value-changed - Fired when user commits a value change. The event is not triggered if `value` property is changed by programmatically.
20 & 21: 
* Fire when "the" user...
* property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/password-field/index.ts
> + * @fires icon-click - Fired when user tapped on icon that added into control's slot.
Fired when "the" user taps~~ped~~ on icon ~~that~~ added into control's slot.****

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/pill/index.ts
> + * @fires clear - Fired when user tapped on cross button.
Fired when "the" user taps~~ped~~ on "clear"~~cross~~ button~~.~~

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/radio-button/index.ts
> + * @fires checked-changed - Fired when the user checked or unchecked the radio. The event is not fired if the `checked` property is changed by programmatically.
Fired when the user checks~~ed~~ or unchecks~~ed~~ the radio. The event is not fired if the `checked` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/rating/index.ts
> + * @fires value-changed - Fired when the user commits a value change. The event is not triggered if `value` property is changed by programmatically.
property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/search-field/index.ts
> + * @fires value-changed - Fired when user commits a value change. The event is not triggered if `value` property is changed by programmatically.
16 to 17
* "the" user
* property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/search-field/index.ts
> + * @fires icon-click - Fired when user tapped on icon that added into control's slot.
Fired when "the" user taps~~ped~~ on icon ~~that~~ added into control's slot.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/select/index.ts
> + * @fires value-changed - Fired when the user commits a value change. The event is not triggered if `value` property is changed by programmatically.
64 & 65: s changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/slider/index.ts
> + * @fires value-changed - Fired when the user commits a value change. The event is not triggered if `value` property is changed by programmatically.
* Fired when the user changes~~d~~
* property is changed ~~by~~ programmatically

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/tab-bar/index.ts
> + * @fires value-changed - Fired at controls when the user changed an active tab. The event is not triggered if `value` property is changed by programmatically.
Fired ~~at controls~~ when the user change"s"~~d~~ an active tab. The event is not triggered if `value` property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/text-field/index.ts
> + * @fires value-changed - Fired when user commits a value change. The event is not triggered if `value` property is changed by programmatically.
24 to 25:
* "the" user
* property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/text-field/index.ts
> + * @fires icon-click - Fired when user tapped on icon that added into control's slot.
Fired when "the" user taps~~ped~~ on icon ~~that~~ added into control's slot.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/time-picker/index.ts
> + * @event value-changed - Fired when the user commits a value change. The event is not triggered if `value` property is changed by programmatically.
roperty is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/toggle/index.ts
> + * @fires checked-changed - Fired when user interacts with the control to check or uncheck. The event is not triggered if `checked` property is changed by programmatically.
is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/tree-select/index.ts
> + * @fires confirm - Fired when user closed a popup with confirmation of new selection.
"the" user close"s"~~d~~ a popup  by ~~with~~ confirming~~ation~~ ~~of~~ the new selection.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/tree-select/index.ts
> + * @fires cancel - Fired when user closed a popup by cancelling the new selection.
save as above: "the" user & close"s"~~d~~

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/tree-select/index.ts
> + * @fires value-changed - Fired when the user commits a value change. The event is not triggered if `value` property is changed by programmatically.
50 - 52: property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/tree-select/index.ts
> + * @fires query-changed - Fired when the user changed value in the input to change a query word. The event is not triggered if `query` property is changed by programmatically.
there is a similar issue in Combo Box. Let's revise them in the same manner.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/tree/elements/tree.ts
> + * @fires value-changed - Fired when the user commits a value change. The event is not triggered if `value` property is changed by programmatically.
23 - 24: property is changed ~~by~~ programmatically.

2022-12-21 07:41 UTC, wattachai-lseg commented on packages/elements/src/tree/elements/tree.ts
> + * @fires expanded-changed - Fired when the user expanded or collapsed item. The event is not triggered if `expanded` property is changed by programmatically.
Fired when the user expand"s"~~ed~~ or collapse"s"~~d~~ item. he event is not triggered if `expanded` property is changed ~~by~~ programmatically.

2022-12-22 06:49 UTC, bualoy-napat commented on packages/elements/src/button/index.ts
> + * @fires active-changed - Fired when `active` property changed by user taps on toggled button. It will not be triggered if `active` state is changed by programmatically.
I don't think we need to describe explicitly for that case. We already stated about the toggled button in the sentence.

2022-12-27 03:11 UTC, wattachai-lseg requested changes
Just a few more things! Also, please take a look at my suggestion for `combo-box` and `tree-select`.

2022-12-27 03:11 UTC, wattachai-lseg commented on packages/elements/src/autosuggest/index.ts
> + * @fires item-highlight - Fired when the user highlight an item or removes highlight from the item.
```suggestion
 * @fires item-highlight - Fired when the user highlights an item or removes highlight from the item.
```

2022-12-27 03:11 UTC, wattachai-lseg commented on packages/elements/src/checkbox/index.ts
> + * @fires checked-changed - Fired when the user checks or unchecks the checkbox. The event is not fired if the checked property is changed programmatically.
```suggestion
 * @fires checked-changed - Fired when the user checks or unchecks the checkbox. The event is not fired if the `checked` property is changed programmatically.
```

2022-12-27 03:11 UTC, wattachai-lseg commented on packages/elements/src/collapse/index.ts
> + * @fires expanded-changed - Fired when the user expanded or collapsed the control. The event is not triggered if `expanded` property is changed programmatically.
```suggestion
 * @fires expanded-changed - Fired when the user expands or collapses the control. The event is not triggered if `expanded` property is changed programmatically.
```

2022-12-27 03:11 UTC, wattachai-lseg commented on packages/elements/src/combo-box/index.ts
> + * @fires query-changed - Fired when the user changes value in the input to change a query word. If `query-debounce-rate` is set, this event will trigger after the time that you set in `query-debounc
```suggestion
 * @fires query-changed - Fired when the user changes value in the input to change a query word. If `query-debounce-rate` is set, this event will be triggered after debounce completion. The event is not triggered if `query` property is changed programmatically.
```

2022-12-27 03:11 UTC, wattachai-lseg commented on packages/elements/src/tab/index.ts
> + * @fires clear - Fired when the user clicks on clear button.
```suggestion
 * @fires clear - Fired when the user clicks on clear button
```

2022-12-27 03:11 UTC, wattachai-lseg commented on packages/elements/src/tree-select/index.ts
> + * @fires query-changed - Fired when the user changes value in the input to change a query word. If `query-debounce-rate` is set, this event will trigger after the time that you set in `query-debounc
```suggestion
 * @fires query-changed - Fired when the user changes value in the input to change a query word. If `query-debounce-rate` is set, this event will be triggered after debounce completion. The event is not triggered if `query` property is changed programmatically.
```

2023-01-03 03:14 UTC, wattachai-lseg approved these changes
LGTM

2023-01-03 03:26 UTC, merged