Chart/migrate demo page
Refinitiv/refinitiv-ui pull request #636
Opened 2023-03-22 22:06 UTC by Theeraphat-Sorasetsakul

## Description

Update demo page to compatible with chartjs v4.

Found that chartjs v4 requires [date adapter](https://github.com/chartjs/awesome#adapters) to support scale type time axes. Comparing on v2, it included with moment.

Fixes # ([STG-200)](https://jira.refinitiv.com/browse/STG-200))

## Type of change

- [x] Refactor (improves code without changing its functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

2023-03-23 08:42 UTC, wattachai-lseg requested changes

2023-03-23 08:42 UTC, wattachai-lseg commented on packages/elements/src/chart/index.ts
> +import 'chartjs-adapter-date-fns';
We might need to work on locale support for `ef-chart` as documented in "Configuration" section of https://www.npmjs.com/package/chartjs-adapter-date-fns?activeTab=readme

2023-03-23 08:42 UTC, wattachai-lseg commented on packages/elements/src/chart/__demo__/index.html
> +      const addDataButton = document.getElementById('addNewDataSet');
```suggestion
      const addDataButton = document.getElementById('addData');
```

2023-03-24 04:46 UTC, Theeraphat-Sorasetsakul commented on packages/elements/src/chart/__demo__/index.html
> +      const addDataButton = document.getElementById('addNewDataSet');
Updated.

2023-03-24 04:47 UTC, wattachai-lseg commented on packages/elements/src/chart/index.ts
> +import 'chartjs-adapter-date-fns';
as EFv 6 doesn't provide builtin locale support, there is no plan to introduce this feature in this v7 release. Marking as resovled.

2023-03-24 08:29 UTC, wattachai-lseg approved these changes
LGTM

2023-03-24 08:36 UTC, merged