fix(combo-box): overwrite icon color on disabled state in solar theme
Refinitiv/refinitiv-ui pull request #91
Opened 2021-11-24 12:52 UTC by bualoy-napat

## Description
This fix also solved the issue of the arrow icon on tree-select that did not display same as combo-box. The color of the arrow icon in the disabled state is similar to the background. So, I overwrote the style of the disabled state and specific on the charcoal. 

Fixes # (issue)
ELF-1674 'Arrow' icon is not displayed in the disabled state on Solar theme(charcoal)
 
## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2021-11-26 03:21 UTC, dtanp-rft requested changes
Style should be consistent with button disabled state.
```
  &[disabled] [part~=icon] {
    opacity: 0.4;
    color: @button-disabled-text-color;
  }
```

2021-11-26 03:45 UTC, bualoy-napat commented
@dtanp-rft I have already updated as your request.

2021-11-30 02:01 UTC, dtanp-rft requested changes
Can we add one unit test to test about `disabled`? Basically, set disabled on combobox and it should set disabled to text-field.

2021-11-30 04:06 UTC, bualoy-napat commented
@dtanp-rft I have already added the unit test and renamed the misspelling file name.

2021-11-30 06:40 UTC, dtanp-rft approved these changes

2021-11-30 06:45 UTC, bualoy-napat commented on packages/elements/src/combo-box/__test__/combo-box.template.test.js
> +    it('Input should be disabled when readonly attribute is set', async () => {
I have fixed it with the current commit.

2021-11-30 07:10 UTC, merged