Feature/enhance validation consistency for field elements
Refinitiv/refinitiv-ui pull request #937
Opened 2023-09-12 03:54 UTC by Sarin-Udompanish

## Description

From Field Elements API Specification changed:

Introduce reportValidity(): A publicly accessible method that allows users to manually trigger validation. It returns a Boolean indicating whether the field is valid or not.
Introduce checkValidity(): Another publicly accessible method, similar to reportValidity(), which checks validity but doesn't display validation error messages. It also returns a Boolean indicating validity.
Number Field Elements API Specification changed:{}

Validation on Input:
The field element should also fire an "error-changed" event when the input value becomes valid after it was previously invalid. This ensures that users can respond to changes in validity in real-time.
Other fields excepts Number Field Specifics changed:

Validation on Initialization:
The field element should not perform validation automatically upon initialization. Users are responsible for initiating validation by calling reportValidity() or checkValidity() when needed.
minlength and maxlength validation:
should only occur when the field's value is changed by a user edit, not when set programmatically. This means that programmatically setting the value should not trigger these specific validation checks. ref: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#setting-minimum-input-length-requirements:-the-minlength-attribute

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2023-09-14 11:27 UTC, wsuwt requested changes

2023-09-14 11:27 UTC, wsuwt commented on documents/src/pages/elements/email-field.md
> +To validate input from users, `ef-email-field` provides similar features to a native input. When a user assigns an invalid input to the control, it will automatically apply an error style to alert th
```suggestion
`ef-email-field` has validation logic similar to native input. When user types invalid value to the control, error style will be shown to notify user. However, if control is being initialised with an invalid value, `reportValidity()` must be called to ensure the error style is applied.
```

2023-09-14 11:27 UTC, wsuwt commented on packages/core/__test__/elements/FormFieldElement.test.js
> +  it('should fired error-changed event when call reportValidity with error stat with no validation', async function () {
```suggestion
  it('should fired error-changed event when call reportValidity() when it is set as error with no constraint', async function () {
```

2023-09-14 11:27 UTC, wsuwt commented on packages/elements/src/number-field/__test__/number-field.test.js
> +    it('Should fired error-changed event when value between valid / invalid', async function () {
```suggestion
    it('Should fired error-changed event when error changes from invalid to valid', async function () {
```

2023-09-14 11:27 UTC, wsuwt commented on packages/elements/src/text-field/__test__/text-field.validation.test.js
> +    it('should show error state on initial when set error attr', async function () {
```suggestion
    it('should show error state on initialisation when error attribute is set', async function () {
```

2023-09-14 11:27 UTC, wsuwt commented on packages/elements/src/text-field/__test__/text-field.validation.test.js
> +    it('should remove error state when call reportValidity with no validation', async function () {
```suggestion
    it('should set error to false when reportValidity() is called with no validation constraint', async function () {
```

2023-09-14 11:27 UTC, wsuwt commented on packages/elements/src/text-field/__test__/text-field.validation.test.js
> +    it('should show error state on initial when set error attr', async function () {
```suggestion
    it('should show error state on initialisation when error attribute is set', async function () {
```

2023-09-14 11:27 UTC, wsuwt commented on packages/elements/src/text-field/index.ts
> +    // This code probably should not be here, as validation must be instantiated by the app developer
Is this comment still valid ?

2023-09-15 06:21 UTC, Sarin-Udompanish commented on packages/core/__test__/elements/FormFieldElement.test.js
> +  it('should fired error-changed event when call reportValidity with error stat with no validation', async function () {
updated

2023-09-15 06:21 UTC, Sarin-Udompanish commented on documents/src/pages/elements/email-field.md
> +To validate input from users, `ef-email-field` provides similar features to a native input. When a user assigns an invalid input to the control, it will automatically apply an error style to alert th
updated

2023-09-15 06:32 UTC, Sarin-Udompanish commented on packages/elements/src/number-field/__test__/number-field.test.js
> +    it('Should fired error-changed event when value between valid / invalid', async function () {
updated

2023-09-15 06:32 UTC, Sarin-Udompanish commented on packages/elements/src/text-field/__test__/text-field.validation.test.js
> +    it('should show error state on initial when set error attr', async function () {
updated

2023-09-15 06:32 UTC, Sarin-Udompanish commented on packages/elements/src/text-field/__test__/text-field.validation.test.js
> +    it('should remove error state when call reportValidity with no validation', async function () {
updated

2023-09-15 06:32 UTC, Sarin-Udompanish commented on packages/elements/src/text-field/__test__/text-field.validation.test.js
> +    it('should show error state on initial when set error attr', async function () {
updated

2023-09-15 06:35 UTC, Sarin-Udompanish commented on packages/elements/src/text-field/index.ts
> +    // This code probably should not be here, as validation must be instantiated by the app developer
removed

2023-09-15 08:52 UTC, wsuwt approved these changes

2023-09-18 02:25 UTC, bualoy-napat commented
LGTM!

2023-09-18 03:46 UTC, merged