docs: revise default values and descriptions
Refinitiv/refinitiv-ui pull request #991
Opened 2023-10-10 07:59 UTC by Sarin-Udompanish

## Description
Review content in API section in all elements

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2023-10-12 11:09 UTC, wattachai-lseg requested changes

2023-10-12 11:09 UTC, wattachai-lseg commented on documents/scripts/element.injector.mjs
> +            if(isEventSection) {
magic string provides more context than a magic number, right?
```suggestion
            if(API_REFERENCE_TITLES[i] === '## Events') {
```

2023-10-12 11:09 UTC, wattachai-lseg commented on documents/scripts/element.injector.mjs
> +const EVENT_WARNING = '::event-warning::';
let's rename to 'event-notice'. it's a something you should know but not as serious as a warning.

2023-10-12 11:09 UTC, wattachai-lseg commented on documents/src/templates/event-warning.md
> +Component events will not trigger when properties are set programmatically.
```suggestion
Property changed events, such as `open-changed` and `value-changed`, will not be triggered when the properties are updated programmatically.
```

2023-10-12 11:09 UTC, wattachai-lseg commented on packages/elements/src/configuration/elements/configuration.ts
> +   * @attr -
As it's a public API, let's change to `@property({attribute: false})`.

2023-10-12 11:09 UTC, wattachai-lseg commented on packages/elements/src/autosuggest/index.ts
> +   * Set attachment target.
```suggestion
   * Target element to be attached with Autosuggest
```

2023-10-12 11:09 UTC, wattachai-lseg commented on packages/elements/src/button/index.ts
> + *
remove empty line?
```suggestion
```

2023-10-12 11:09 UTC, wattachai-lseg commented on packages/elements/src/chart/elements/chart.ts
> +   * List of line colors
line colors won't apply to some chart types such as pie & bubble charts.
```suggestion
   * List of available colors for chart styling
```

2023-10-12 11:09 UTC, wattachai-lseg commented on packages/elements/src/clock/index.ts
> +   * Shifts displayed time by seconds without changing the original value
```suggestion
   * number of seconds that the display time should be offset from the original value
```

2023-10-12 11:09 UTC, wattachai-lseg commented on packages/elements/src/autosuggest/index.ts
>     * @default More results for {0}
What is `{0}`? Is there a way could describe it in a better way?

2023-10-12 11:09 UTC, wattachai-lseg commented on packages/elements/src/combo-box/index.ts
> +   * Control query rate
```suggestion
   * Control query rate in milliseconds
```

2023-10-12 11:09 UTC, wattachai-lseg commented on packages/elements/src/pagination/index.ts
> +   * Maximum page value
```suggestion
   * Maximum page limit
```

2023-10-16 03:38 UTC, Sarin-Udompanish commented on documents/src/templates/event-warning.md
> +Component events will not trigger when properties are set programmatically.
I think the example ( such as `open-changed` and `value-changed** ) is not correct. Events that don't have `-changed prefix` also not fired when properties are updated programmatically. In another word all events should not be triggered when the properties are updated programmatically.

2023-10-16 03:44 UTC, Sarin-Udompanish commented on packages/elements/src/configuration/elements/configuration.ts
> +   * @attr -
Let's do that in another story as It not related to the documentation. The reason that I added @attr - is a workaround to make the api-anlyzer to generate `attribute` column.

2023-10-16 03:49 UTC, Sarin-Udompanish commented on packages/elements/src/button/index.ts
> + *
We tend to leave an empty line to seperate between event and property section.

2023-10-16 06:52 UTC, Sarin-Udompanish commented on packages/elements/src/autosuggest/index.ts
>     * @default More results for {0}
That the actual default value of this property.

2023-10-16 10:52 UTC, wattachai-lseg commented on packages/elements/src/autosuggest/index.ts
>     * @default More results for {0}
it comes from this phrasebook? Maybe we could change it to `More results for {query}` instead? It's still a source code but `query` is definitely better than `0`
```javascript
const translations = {
  LOADING: 'Loading suggestion items',
  MORE_RESULTS: 'More results for <mark>{ query }</mark>'
};
````

2023-10-16 10:58 UTC, wattachai-lseg commented on packages/elements/src/configuration/elements/configuration.ts
> +   * @attr -
I understand that this is clearly out of scope. Yet, it's a tiny change. Can't we piggyback on this PR?

2023-10-17 02:49 UTC, wattachai-lseg commented on documents/src/templates/event-warning.md
> +Component events will not trigger when properties are set programmatically.
`add-attach-target-events` of Autosuggest component fires even when `attach` prop is updated programmatically. We need to find a way to handle this exception and I'm afraid there could be more.

2023-10-17 07:24 UTC, wattachai-lseg commented on documents/scripts/element.injector.mjs
> +            if(isEventSection) {
resolving this as it's no longer relevant.

2023-10-17 07:24 UTC, wattachai-lseg commented on documents/scripts/element.injector.mjs
> +const EVENT_WARNING = '::event-warning::';
resolving this as it's no longer relevant.

2023-10-17 07:24 UTC, wattachai-lseg commented on documents/src/templates/event-warning.md
> +Component events will not trigger when properties are set programmatically.
resolving this as it's no longer relevant.

2023-10-17 07:33 UTC, wattachai-lseg commented on packages/elements/src/configuration/elements/configuration.ts
> +   * @attr -
new issue created for this issue: https://jira.refinitiv.com/browse/ELF-2316

2023-10-17 08:12 UTC, wattachai-lseg commented on packages/elements/src/button/index.ts
> + * @fires active-changed - Fired when `active` property changed by user taps on toggled button.
I could confirm that the event doesn't fire when `active` is updated programmatically.  Why did we change it?

2023-10-17 08:12 UTC, wattachai-lseg commented on packages/elements/src/chart/elements/chart.ts
> +   * @returns {string[]} List of line colors
```suggestion
   * @returns {string[]} List of available colors for chart styling
```

2023-10-17 08:12 UTC, wattachai-lseg commented on packages/elements/src/select/index.ts
> +  public get label(): string | undefined {
I can't find any scenarios when this could be `undefined`.

2023-10-17 08:39 UTC, wattachai-lseg commented on packages/elements/src/select/index.ts
> +  public get label(): string | undefined {
my  bad, this would be `undefined` when labels is an empty array.

2023-10-17 08:43 UTC, wattachai-lseg submitted a review, later dismissed

2023-10-18 08:34 UTC, wsuwt commented on packages/elements/src/appstate-bar/index.ts
> +   * Type of state bar. Supported value are `info`, `highlight`.
Supported values are already mentioned in type column.

```suggestion
   * Type of state bar.
```

2023-10-20 10:18 UTC, wsuwt approved these changes

2023-10-20 10:23 UTC, merged